### ISSUE TITLE
Double clicking on split curve in model panel causes curve to be unselectable

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tomate44/CurvesWB#109] opened 2023-12-20 23:23 UTC
When a split curve is created, double clicking (as to try to edit it like it's possible with freehand B-Spline) it can cause it to be unselectable in 3D view, even after closing and reopening the file. This means the issue is saved in the file itself.

Example:  [unselectable_split_curve.FCStd.zip](https://github.com/tomate44/CurvesWB/files/13733461/unselectable_split_curve.FCStd.zip)

**Comment by tomate44** [comment] 2024-10-10 16:04
I cannot reproduce.
It is probably fixed in latest version.

**Closed by tomate44** 2024-10-10 16:04 UTC
